class VerMenu {
  String? id;
  String? name;
  String? time;
  String? ingredients;
  String? decription;

  VerMenu(
      {required this.id,
      required this.name,
      required this.time,
      required this.ingredients,
      required this.decription});

  static List<VerMenu> vmenuList() {
    return [
      VerMenu(
          id: "assests/Rasagulla.png",
          name: "Rasugulla",
          time: "time",
          ingredients: "4 cups full-fat milk\n2 tablespoons lemon juice\n1 cup sugar\n4 cups water\n4-5 green cardamom pods, lightly crushed\nA few strands of saffron (optional)\nChopped pistachios or almonds for garnishing (optional) ",
          decription: "In a large pot, bring the milk to a boil over medium heat. Stir occasionally to prevent it from sticking to the bottom. \nOnce the milk comes to a boil, reduce the heat to low and add lemon juice gradually while stirring. The acid in the lemon juice will cause the milk to curdle. \nContinue stirring gently until the milk solids (paneer) separate from the whey. The whey should appear transparent. \nTurn off the heat and let it rest for a minute. Place a muslin cloth or cheesecloth over a large bowl or colander. \nPour the curdled milk into the cloth-lined bowl or colander. Gather the cloth corners and squeeze out the excess whey. Be careful not to burn yourself, as the milk will be hot. \nRinse the paneer under cold running water to remove the lemony flavor. \nTwist the cloth tightly and hang it for about 1 hour to drain any remaining whey. This step is crucial to ensure the right texture of the paneer. \nAfter an hour, remove the paneer from the cloth and knead it on a clean surface for 5-7 minutes until it becomes smooth and there are no lumps. This process is called chhana. \nDivide the chhana into small equal-sized balls and roll them between your palms until they are smooth and crack-free. The balls should be smaller in size, as they will expand when cooked. \nIn a large pot, combine sugar, water, crushed cardamom pods, and saffron strands (if using). Place it over medium heat and stir until the sugar dissolves completely. \nOnce the sugar syrup comes to a boil, reduce the heat to low and gently drop the chhana balls into the syrup one by one. \nCover the pot with a lid and let the rasgullas cook for about 15-20 minutes. They will increase in size while cooking. \nRemove the lid and let the rasgullas cool down in the syrup for at least 1-2 hours. This will allow them to absorb the syrup and become soft. \nGarnish the rasgullas with chopped pistachios or almonds, if desired. \nServe chilled or at room temperature."),
      VerMenu(
          id: "assests/gulab-jamun.png",
          name: "Gulab Jamun",
          time: "time",
          ingredients: "1 cup milk powder\n1/4 cup all-purpose flour\n1/4 teaspoon baking soda\n2 tablespoons ghee (clarified butter)\n3-4 tablespoons milk (as needed to make a dough)\nOil or ghee for deep frying\n1 cup sugar\n1 cup water\n1/2 teaspoon cardamom powder\nA few strands of saffron (optional)\nChopped pistachios or almonds for garnishing (optional)",
          decription: "1.In a mixing bowl, combine the milk powder, all-purpose flour, and baking soda. Mix them well. \n2. Add the ghee to the mixture and rub it in with your fingertips until the mixture resembles bread crumbs. \n3. Gradually add milk, a tablespoon at a time, and knead the mixture into a soft dough. The dough should be smooth and slightly sticky. Add more milk if needed. \n4. Cover the dough with a damp cloth and let it rest for about 15 minutes. \n5. Meanwhile, prepare the sugar syrup. In a saucepan, add sugar and water. Place it over medium heat and stir until the sugar dissolves completely. \n6. Add cardamom powder and saffron strands to the sugar syrup, and let it simmer for about 5 minutes. Then, turn off the heat and set the syrup aside. \n7. Heat oil or ghee in a deep pan or kadai over medium heat for frying the gulab jamuns. \n8. Divide the dough into small portions and shape them into smooth balls without any cracks. Make sure the balls are not too big, as they will expand when fried and soaked in syrup. \n9. Once the oil or ghee is hot, reduce the heat to low. Gently add the gulab jamun balls into the oil or ghee and fry them until they turn golden brown. Stir occasionally to ensure even browning. \n10. Once the gulab jamuns are fried, remove them from the oil or ghee using a slotted spoon and drain excess oil by placing them on a paper towel. \n11. Heat the sugar syrup again over low heat. Add the fried gulab jamuns to the syrup and let them soak for at least 20-30 minutes. You can also keep them soaked for a longer duration for a richer flavor. \n12. Garnish the gulab jamuns with chopped pistachios or almonds, if desired. \n13. Serve warm or at room temperature"),
      VerMenu(
          id: "assests/paneerBhurji.png",
          name: "Paneer Bhurji",
          time: "time",
          ingredients: " 200 grams paneer, cubed\n2 tablespoons ghee or butter\n1 teaspoon cumin seeds\n1 medium onion, finely chopped\n2 teaspoons ginger-garlic paste\n2 medium tomatoes, pureed\n1/4 cup tomato puree (optional, for added richness)\n1/2 teaspoon turmeric powder\n1 teaspoon red chili powder (adjust to taste)\n1 teaspoon Kashmiri red chili powder (for vibrant color, optional)\n1 teaspoon garam masala\n1/2 teaspoon dried fenugreek leaves (kasuri methi)\n1/2 cup heavy cream\nSalt to taste\nFresh coriander leaves, chopped for garnishing",
          decription: "Heat oil or ghee in a pan over medium heat.\nAdd cumin seeds and let them splutter.\nAdd finely chopped onions and sauté until they turn translucent.\nAdd green chili and ginger-garlic paste. Sauté for a minute until the raw smell disappears.\nAdd the finely chopped tomatoes and cook until they become soft and mushy.\nAdd turmeric powder, red chili powder, garam masala, and salt. Mix well and cook for a minute to allow the spices to blend.\nReduce the heat to low and add the crumbled paneer to the pan. Mix gently to coat the paneer with the spices.\nCook for a few more minutes, stirring occasionally, until the paneer is heated through.\nTaste and adjust the seasoning if needed.\nRemove from heat and garnish with fresh coriander leaves.\nServe hot with roti, paratha, or bread."),
      VerMenu(
          id: "assests/Dosa.png",
          name: "Dosa ",
          time: "time",
          ingredients: "For the Dosa Batter:\n1 cup regular rice (not basmati)\n1/2 cup urad dal (split black lentils)\n1/4 teaspoon fenugreek seeds (optional, for fermentation)\nWater (for soaking and grinding)\nSalt to taste\n\nFor Making Dosas:\nDosa batter\nOil or ghee (clarified butter) for cooking\nOptional fillings: chopped onions, chopped tomatoes, grated cheese, etc. (as desired)",
          decription: "Preparing the Dosa Batter:\n1. Wash the rice, urad dal, and fenugreek seeds (if using) separately under running water.\n2. Soak the rice, urad dal, and fenugreek seeds in enough water for at least 4-6 hours. You can soak them overnight for convenience.\n3. After soaking, drain the water from the rice and urad dal separately.\n4. Grind the rice and urad dal separately to a smooth paste using a blender or wet grinder. You can add a little water as needed while grinding.\n5. Mix the ground rice and urad dal batter together in a large bowl. Add salt and mix well.\n6. Cover the bowl and let the batter ferment in a warm place for 8-12 hours or overnight. The batter will rise and become slightly airy.\n7. Once fermented, mix the batter gently, and it's ready to be used for making dosas.\n\nMaking Dosas:\n1. Heat a dosa tawa (flat griddle) or a non-stick skillet on medium heat.\n2. Once the tawa is hot, take a ladleful of dosa batter and pour it onto the center of the tawa.\n3. Using the back of the ladle, spread the batter in a circular motion to form a thin, even layer. You can make the dosa as small or as large as you prefer.\n4. Drizzle a little oil or ghee around the edges of the dosa and a few drops on top.\n5. Cook the dosa on medium heat until the bottom turns golden brown and crisp.\n6. Add any desired fillings like chopped onions, tomatoes, or grated cheese on the dosa.\n7. Gently fold the dosa over the fillings to form a half-moon shape or roll it up like a wrap.\n8. Cook for another minute or so until the fillings are heated through and any cheese has melted.\n9. Remove the dosa from the tawa and repeat the process with the remaining batter.\n10. Serve hot dosas with sambar, coconut chutney, or any chutney of your choice."),
      VerMenu(
          id: "assests/manchurian.png",
          name: "Manchurian",
          time: "time",
          ingredients: "For the Vegetable Balls:\n1 cup finely chopped mixed vegetables (carrots, cabbage, capsicum, beans, etc.)\n1/4 cup all-purpose flour\n1/4 cup cornflour\n1 teaspoon ginger-garlic paste\n1 teaspoon soy sauce\n1/2 teaspoon red chili powder\nSalt to taste\nOil for deep frying\n For the Manchurian Sauce:\n2 tablespoons oil\n1 tablespoon finely chopped garlic\n1 tablespoon finely chopped ginger\n1 small onion, finely chopped\n1/4 cup chopped capsicum (bell pepper)\n2 tablespoons soy sauce\n1 tablespoon tomato ketchup\n1 tablespoon chili sauce (adjust to taste)\n1/2 teaspoon vinegar\n1/2 teaspoon sugar\nSalt to taste\n1 cup water\n2 teaspoons cornflour mixed with 2 tablespoons water (for thickening)\nChopped spring onions for garnishing",
          decription: ""),
      VerMenu(
          id: "assests/manchowSoup.png",
          name: "Manchow Soup",
          time: "time",
          ingredients: "For the Soup:\n2 tablespoons oil\n2 cloves garlic, minced\n1-inch piece of ginger, grated\n1 small onion, finely chopped\n1/4 cup finely chopped cabbage\n1/4 cup finely chopped carrots\n1/4 cup finely chopped capsicum (bell pepper)\n1/4 cup finely chopped beans\n2-3 green chilies, finely chopped (adjust to taste)\n2 tablespoons soy sauce\n1 tablespoon vinegar\n1 tablespoon chili sauce (adjust to taste)\n1 teaspoon black pepper powder\n4 cups vegetable or chicken broth\nSalt to taste\nChopped spring onions for garnishing\n\nFor the Noodles:\n1/2 cup boiled noodles (thin or flat)\n1 tablespoon oil",
          decription: "In a mixing bowl, combine the finely chopped mixed vegetables, all-purpose flour, cornflour, ginger-garlic paste, soy sauce, red chili powder, and salt. Mix well to form a dough-like consistency.\nShape the mixture into small, bite-sized balls and set them aside.\nHeat oil for deep frying in a wok or pan. Once the oil is hot, carefully add the vegetable balls in batches and fry until they turn golden brown and crisp. Drain on a paper towel to remove excess oil.\nIn a separate pan, heat 2 tablespoons of oil. Add the finely chopped garlic and ginger. Sauté for a minute until they turn aromatic.\nAdd the chopped onion and capsicum (bell pepper). Stir-fry on high heat for 2-3 minutes until they are slightly cooked but still retain their crunch.\nAdd soy sauce, tomato ketchup, chili sauce, vinegar, sugar, and salt. Mix well to combine all the sauces.\nIn a cup, mix 2 teaspoons of cornflour with 2 tablespoons of water to make a slurry. Add the slurry to the pan and mix quickly to thicken the sauce.\nPour in the water and bring the sauce to a boil. Cook for a few minutes until the sauce thickens and becomes glossy.\nAdd the fried vegetable balls to the sauce and toss gently to coat them evenly with the sauce.\nGarnish with chopped spring onions.\nServe Vegetable Manchurian hot as an appetizer or as a side dish with fried rice or noodles."),
      VerMenu(
          id: "assests/paneerMakhani.png",
          name: "Paneer Makhani",
          time: "time",
          ingredients: " 200 grams paneer, cubed\n2 tablespoons ghee or butter\n1 teaspoon cumin seeds\n1 medium onion, finely chopped\n2 teaspoons ginger-garlic paste\n2 medium tomatoes, pureed\n1/4 cup tomato puree (optional, for added richness)\n1/2 teaspoon turmeric powder\n1 teaspoon red chili powder (adjust to taste)\n1 teaspoon Kashmiri red chili powder (for vibrant color, optional)\n1 teaspoon garam masala\n1/2 teaspoon dried fenugreek leaves (kasuri methi)\n1/2 cup heavy cream\nSalt to taste\nFresh coriander leaves, chopped for garnishing",
          decription: "Heat ghee or butter in a pan over medium heat.\nAdd cumin seeds and let them splutter.\nAdd finely chopped onions and sauté until they turn golden brown.\nAdd ginger-garlic paste and sauté for a minute until the raw smell disappears.\nAdd tomato puree and cook for a few minutes until the oil starts to separate from the mixture.\nAdd turmeric powder, red chili powder, Kashmiri red chili powder (if using), garam masala, and salt. Mix well and cook for a minute to allow the spices to bloom.\nAdd the tomato puree (if using) and mix well. Cook for a few more minutes until the flavors are well blended.\nReduce the heat to low and add the cubed paneer to the pan. Mix gently to coat the paneer with the gravy.\nCrush the dried fenugreek leaves between your palms and add them to the pan. This will add a distinctive flavor to the dish.\nPour in the heavy cream and stir well. Simmer for 3-4 minutes to allow the flavors to meld together.\nTaste and adjust the seasoning if needed.\nRemove from heat and garnish with fresh coriander leaves.\nServe hot with naan, roti, or rice.")
    ];
  }
}
